name: Provider Acceptance Test

on: workflow_call


jobs:
  test:
    name: Run formal acceptance test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Check out code
        uses: actions/checkout@v3

      # - name: Set up Terraform latest
      #   uses: hashicorp/setup-terraform@v2

      - name: Acceptance test
        run: |
          make testacc

      # - name: Check changed files
      #   uses: tj-actions/verify-changed-files@v14
      #   id: check-changed-files
      #   with:
      #     files: |
      #       internal/broker/generated

      # - name: Run step only when any of the above files change.
      #   if: steps.check-changed-files.outputs.files_changed == 'true'
      #   run: |
      #     echo "Changed files: ${{ steps.check-changed-files.outputs.changed_files }}"

      # - name: Commit back any updated source code
      #   if: steps.check-changed-files.outputs.files_changed == 'true'
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     committer_name: GitHub Actions
      #     committer_email: actions@github.com
      #     message: 'Updating generated source [skip ci]'
      #     add: 'internal/broker/generated/*.go'
      #     new_branch: GeneratedSourceUpdates-${{ github.ref_name }}

      # - name: Create pull request
      #   if: steps.check-changed-files.outputs.files_changed == 'true'
      #   run: |
      #     CURRENT_BRANCH=${GITHUB_REF_NAME}
      #     gh pr create -B ${CURRENT_BRANCH} -H "GeneratedSourceUpdates-${CURRENT_BRANCH}" --title "Merge generated source updates into ${CURRENT_BRANCH}" --body 'Created by Github action'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
